### ISSUE TITLE
[Request] Adding Support for .fco files on Sonic Unleashed

### ISSUE THREAD

**Issue by at-wr** [brianuuu/fcoEditor#1]
Hmm, I know fcoEditor currently doesn't support **Sonic Unleashed**'s .fco files.
But I want to know _if it is possible to support SU_ or _it will support in the future_. 
It would be great if "yes". XD

**Comment by brianuuu** [comment]
Probably not, Unleashed has the worst structure setup for subtitles, instead of a global table for all character used in game they made separate table per scenario per language and only have characters used in that scenario, even if you can load the .fco files you are extremely limited in what characters you can use.
